IFMEM_CORE_PATH       =   $(SSC_ROOT)\MemIf

IFMEM_OUTPUT_PATH     =   $(GENDATA_DIR)

SSC_PLUGINS        +=

MEMIF_DEPENDENT_PLUGINS =

CC_INCLUDE_PATH     +=  $(IFMEM_CORE_PATH)  $(IFMEM_OUTPUT_PATH)
CPP_INCLUDE_PATH    +=
ASM_INCLUDE_PATH    +=
